resource_types:
  - name: maven
    type: docker-image
    source:
      repository: twic/maven-repo-resource
      tag: "1"

resources:
  - name: source-code
    type: git
    source:
      uri: {{GIT_REPO}}
      branch: {{GIT_BRANCH}}

  - name: deploy-dev-app
    type: cf
    source:
      api: {{CF_API}}
      username: {{CF_USER}}
      password: {{CF_PASS}}
      organization: {{CF_DEV_ORG}}
      space: {{CF_DEV_SPACE}}
      skip_cert_check: true

jobs:
  - name: unit-tests
    plan:
    - get: source-code
      trigger: true
    - task: run-tests
      privileged: true
      file: source-code/ci/tasks/unit.yml
    - put: deploy-dev-app
      params:
        manifest: source-code/manifest.yml
        path: build/spring-music.war
        current_app_name: spring-music
